### ISSUE TITLE
Missing javascript?

### ISSUE THREAD

**Issue by aptonline** [AZSupra/HADashboard-Dark-Theme1#1]
Just installed the Dark Theme and noticed a missing reference to a javascript file in variables.yaml

` <script type="text/javascript" src="/custom_css/blur1/js/helpers.js"></script>
`

Is this intentional?

Thanks
Ade

**Comment by AZSupra** [comment]
Thanks for catching that. The helper.js reference is left over from another theme I modified to create this one. That line should be safe to remove. When I'll get home I'll verify that I don't currently use this in my setup.

**Comment by aptonline** [comment]
Thanks thats working :)
